# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    async def ExtractDomain(self, system_prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> types.AdvisorDomain:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ExtractDomain(system_prompt=system_prompt,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractDomain", args={
                "system_prompt": system_prompt,
            })
            return typing.cast(types.AdvisorDomain, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def SynthesizeTrainingData(self, name: str,primary_domain: str,expertise_areas: str,communication_style: str,target_audience: str,research: str,system_prompt: str,num_examples: int,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.TrainingExample"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.SynthesizeTrainingData(name=name,primary_domain=primary_domain,expertise_areas=expertise_areas,communication_style=communication_style,target_audience=target_audience,research=research,system_prompt=system_prompt,num_examples=num_examples,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="SynthesizeTrainingData", args={
                "name": name,"primary_domain": primary_domain,"expertise_areas": expertise_areas,"communication_style": communication_style,"target_audience": target_audience,"research": research,"system_prompt": system_prompt,"num_examples": num_examples,
            })
            return typing.cast(typing.List["types.TrainingExample"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractDomain(self, system_prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.AdvisorDomain, types.AdvisorDomain]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractDomain", args={
            "system_prompt": system_prompt,
        })
        return baml_py.BamlStream[stream_types.AdvisorDomain, types.AdvisorDomain](
          __result__,
          lambda x: typing.cast(stream_types.AdvisorDomain, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AdvisorDomain, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def SynthesizeTrainingData(self, name: str,primary_domain: str,expertise_areas: str,communication_style: str,target_audience: str,research: str,system_prompt: str,num_examples: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.List["stream_types.TrainingExample"], typing.List["types.TrainingExample"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="SynthesizeTrainingData", args={
            "name": name,"primary_domain": primary_domain,"expertise_areas": expertise_areas,"communication_style": communication_style,"target_audience": target_audience,"research": research,"system_prompt": system_prompt,"num_examples": num_examples,
        })
        return baml_py.BamlStream[typing.List["stream_types.TrainingExample"], typing.List["types.TrainingExample"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.TrainingExample"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.TrainingExample"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ExtractDomain(self, system_prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractDomain", args={
            "system_prompt": system_prompt,
        }, mode="request")
        return __result__
    async def SynthesizeTrainingData(self, name: str,primary_domain: str,expertise_areas: str,communication_style: str,target_audience: str,research: str,system_prompt: str,num_examples: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="SynthesizeTrainingData", args={
            "name": name,"primary_domain": primary_domain,"expertise_areas": expertise_areas,"communication_style": communication_style,"target_audience": target_audience,"research": research,"system_prompt": system_prompt,"num_examples": num_examples,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ExtractDomain(self, system_prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractDomain", args={
            "system_prompt": system_prompt,
        }, mode="stream")
        return __result__
    async def SynthesizeTrainingData(self, name: str,primary_domain: str,expertise_areas: str,communication_style: str,target_audience: str,research: str,system_prompt: str,num_examples: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="SynthesizeTrainingData", args={
            "name": name,"primary_domain": primary_domain,"expertise_areas": expertise_areas,"communication_style": communication_style,"target_audience": target_audience,"research": research,"system_prompt": system_prompt,"num_examples": num_examples,
        }, mode="stream")
        return __result__
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))