# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class AdvisorDomain(BaseModel):
    name: typing.Optional[str] = Field(default=None, description='Advisor\'s full name')
    primary_domain: typing.Optional[str] = Field(default=None, description='Main area of expertise, e.g. \'burnout recovery\'')
    expertise_areas: typing.List[str] = Field(description='3-5 specific topics they cover')
    communication_style: typing.Optional[str] = Field(default=None, description='How they communicate, e.g. \'warm and empathetic\'')
    target_audience: typing.Optional[str] = Field(default=None, description='Who they typically help')
    key_themes: typing.List[str] = Field(description='Recurring concepts in their advice')

class TrainingExample(BaseModel):
    instruction: typing.Optional[str] = Field(default=None, description='Realistic user question or situation')
    response: typing.Optional[str] = Field(default=None, description='Advisor\'s response in their authentic voice')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
