# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (2)
# #########################################################################

class AdvisorDomain(BaseModel):
    name: str = Field(description='Advisor\'s full name')
    primary_domain: str = Field(description='Main area of expertise, e.g. \'burnout recovery\'')
    expertise_areas: typing.List[str] = Field(description='3-5 specific topics they cover')
    communication_style: str = Field(description='How they communicate, e.g. \'warm and empathetic\'')
    target_audience: str = Field(description='Who they typically help')
    key_themes: typing.List[str] = Field(description='Recurring concepts in their advice')

class TrainingExample(BaseModel):
    instruction: str = Field(description='Realistic user question or situation')
    response: str = Field(description='Advisor\'s response in their authentic voice')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
